version: '3.9' # Specify the version of Docker Compose

services:
  oracle-db:
    image: gvenzl/oracle-xe:slim
    container_name: oracle-db
    environment:
      ORACLE_PASSWORD: "admin"
      ORACLE_ALLOW_REMOTE: true
      ORACLE_DISABLE_ASYNCH_IO: true
      ORACLE_ENABLE_XDB: true
      ORACLE_MEMORY: 512
    ports:
      - "1521:1521"    # Port for SQL*Net
      - "5500:5500"    # Port for Oracle Enterprise Manager
    volumes:
      - oracle_data:/opt/oracle/oradata  # Persistent storage for Oracle Database data files
    networks:
      - oracle-network
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s /nolog"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  oracle_data:
    driver: local

networks:
  oracle-network:
    external: true
